version: '3'
services:
  notebook:
    build: .
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
    volumes:
      - ./data/:/data/
      - ./://home/jovyan/
    ports:
      - "8888:8888"
    depends_on:
      - postgres
  postgres:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=
    volumes:
      - ./postgres_storage/:/var/lib/postgresql/data/
    ports:
      - "54320:5432"
